### PR TITLE
feat: created basic sponsors page

### PR DESCRIPTION
**Pull request by Naeviant**
resolves issue #8

### CODE REVIEW

**Comment by Naeviant** [comment]
This is pretty barebones at the moment, but that is a consequence of the global theme not being ready yet.

**Comment by ary4n99** [comment]
Since there is no effect to clicking the sponsor cards, could you please remove the ripple when the card is clicked?
Could you also please use createStyles rather than defining inline styles? [Documentation here](https://material-ui.com/styles/api/#createstyles-styles-styles)
Also, please use descriptive state names, e.g. [sponsors, setSponsors]
Lastly, could you please avoid using div as a wrapper, instead using a JSX fragment <>...</>

**Review by ary4n99 — CHANGES_REQUESTED** [review]
Since there is no effect to clicking the sponsor cards, could you please remove the ripple when the card is clicked?

Could you also please use createStyles rather than defining inline styles? Documentation here

Also, please use descriptive state names, e.g. [sponsors, setSponsors]

Additionally, could you please use absolute imports rather than relative ones, e.g. src/pages/sponsors/SponsorCard. This will make it easier to reference components from the components folder and will provide consistency to the code.

Lastly, could you please avoid using div as a wrapper, instead using a JSX fragment <>...</>

**Comment by Naeviant** [comment]
Strangely, Git seems to think I made some of the edits before you had even sent your review!

Thanks for the review. All of the changes requested have been made. Additionally, I've changed some image alt text which I'd missed.

**Review by ary4n99 — APPROVED** [review]

**Comment by ary4n99** [comment]
Thanks for making the changes!

**Pull request merged**
