### PR TITLE
Create initial dashboard

### PR DESCRIPTION
**Pull request by ary4n99**

### CODE REVIEW

**Review by Naeviant — CHANGES_REQUESTED** [review]
A huge improvement on what was there before!

Just a few things before I approve this:

- The mockups we received from the graphics team would suggest the Discord server link should be in the header bar. I would say this makes the button on the dashboard page redundant.
- The submissions and Discord buttons on the dashboard page have broken URLs.
- Could the cards on the dashboard all be the same height? I think this would make it look better.
- The buttons on the submission page have some weird behaviour when the window size is decreased.

**Comment by ary4n99** [comment]
I've fixed most of these issues, but let's merge this branch now and move the discord button to the topbar later if needed, as the mockup design isn't final yet.

**Review by Naeviant — APPROVED** [review]
Thanks for making those changes.

I see you've renamed #10 to remind us to move the Discord link later (if required), so I think this is good for merging now. 👍

**Comment by Naeviant** [comment]
Unlinked #28 issue as the topbar currently doesn't contain anything.

**Pull request merged**
