### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by v8runn**
Created the landing page for the hackathon. Overall page requires colour scheme and font change. The launch component requires a background image with an opacity with the register button on top of it with a countdown to the hackathon.

### CODE REVIEW

**Review by ary4n99 — CHANGES_REQUESTED** [review]
Great work! 

Just a few changes required:
- There is a white border around the whole page, you can use `<CssBaseline/>` to get rid of that
- You can insert the placeholder text from [GreatUniHack 2020](https://greatunihack.com) so that the page looks more populated for now
- There is a partial shadow in the top left under the navbar due to the register button's white box/background, you make those two a single component as they won't be reused anywhere else in the code
2021-08-31 10_33_00-GreatUniHack 2021
- If you can, make the imports absolute, this improves code readability
- For the FAQs, you could reuse a card component with a `.json` file for the data rather than repeating the code for the boxes
- Some styles are inline, these could be added to the `useStyle`
- The navbar buttons are on the left, these should be on the right
- You should also add a sponsors section under the FAQ
- You can use the old logo and the date 15 October for the countdown for the hero section (the final date/time of the hackathon will be modified later), 
2021-08-31 10_49_43-generic website mock-ups - Google Slides
(ignore the discord logo as that will likely be applicants only, you can also move the login button to under the apply button)
- Also add FAQ to the topbar and remove dashboard/login, so it needs to have the same buttons as last year's website:
2021-08-31 10_53_46-GreatUniHack 2020
- Add social logos/links to the footer and centre the text, you can also add the contact email there

**Comment by v8runn** [comment]
Made the following changes:

- Removed the white border around the whole page.
- Populated page with info from last year's website.
-  Fixed the build errors.
- NavBar buttons pushed to the right.
- Sponsors section added. Created a new component just for the landing page instead of using the ones created for the dashboard to retain the modularity of the page with a reduced card size and without the sponsors description.
- Added countdown and logo to landing page.
- Added social media handles to the footer and made some style mods.
- Improved code readability for the FAQ section by creating a separate .tsx file for the data.
- Some of the styles maybe inline because I didn't want to create a section in useStyles just for a single style mod.

**Review by ary4n99 — CHANGES_REQUESTED** [review]
Great work, it looks much better! There's still some changes required before merging, though:
- Could you make the sponsor column aligned like in the Google Slides & sponsors page (each sponsor vertically)
- Could you make the countdown date an environment variable (making it easier to use for another hackathon)
- There is still a white border on the bottom & right side of the page, with horizontal scrollbars appearing - these shouldn't be there 
2021-09-01 19_45_04-GreatUniHack 2021
- There are still some styles used inline, these should be in the makeStyles
- The footer text should be centred, with the social buttons being on the top, under which would be the contact email (hackathons@unicsmcr.com) and then finally the copyright text
- The social icons could be bigger, and they should take users to the following pages in a new tab: 
  - https://www.facebook.com/unicsmcr/
  - https://www.instagram.com/unicsmcr/
- The navbar buttons still redirect to the wrong pages & some of them aren't required, such as login. The buttons should be as shown below
131473253-1ac8db4d-955c-44dd-b0a0-5001b16063e2 (these buttons should also scroll smoothly to the appropriate section rather than jumping there without animation - none of the buttons should redirect the user to another page, other than the social links)
- Could you make the logo for the hero section take half the horizontal space, with the date, countdown etc. taking up the other half

**Review by Naeviant — CHANGES_REQUESTED** [review]
Agreed with @ary4n99's comments. Also just a couple more from me:

- You're storing sponsor data in ` src/components/landing/SponsorsData.tsx` which already exists in `src/pages/sponsors/SponsorData.json`. Could the data be shared so that we're not having to store/update duplicate data?
- Could the social media icons have the mouse pointer change to indicate that they are clickable?

**Comment by v8runn** [comment]
- Fixed the white border issues, added the icons to the navbar and updated the buttons, removed inline styling ,  added smooth scrolling and aligned the elements in the launch component.

I still need to make the timer an env variable and make changes to the footer according to the wireframe. But I pushed these changes now to work on the contact page before coming back to this when we get the colour schemes etc from the graphics team. Should be a couple days' work and should complete this way before the end of this month.

**Pull request merged**
